template-file-path: infra/root.yml

parameters:
  EnvironmentName: prod
  TemplatesBucket: fotos-cfn-templates-593793048595
  TemplatesPrefix: templates
  AppName: fotos
  GitHubOrg: EkowSackey
  GitHubRepo: photo-uploader-app

tags:
  Environment: prod
  Project: fotos
  ManagedBy: CloudFormation-GitSync
