template-file-path: infra/root.yml

parameters:
  EnvironmentName: prod
  TemplatesBucket: fotos-cfn-templates
  TemplatesPrefix: templates
  AppName: fotos
  GitHubOrg: EkowSackey
  GitHubRepo: photo-uploader-app
  CreateOIDCProvider: 'false'

tags:
  Environment: prod
  Project: fotos
  ManagedBy: CloudFormation-GitSync
